import { BlockedFileResult } from '../config/types';
import { Logger } from './logger';

/**
 * Posts PR review comments when ProcessContent returns block actions.
 */
export class PrCommentService {
  private readonly logger: Logger;

  constructor(
    private readonly octokit: ReturnType<typeof import('@actions/github').getOctokit>,
    private readonly owner: string,
    private readonly repo: string,
    private readonly prNumber: number
  ) {
    this.logger = new Logger('PrCommentService');
  }

  /**
   * Post a review comment on the PR listing all blocked files with policy details.
   */
  async postBlockedFilesReview(blockedFiles: BlockedFileResult[]): Promise<void> {
    if (blockedFiles.length === 0) return;

    this.logger.info(`Posting review comment for ${blockedFiles.length} blocked file(s) on PR #${this.prNumber}`);

    const body = this.formatBlockedFilesComment(blockedFiles);

    try {
      await this.octokit.rest.pulls.createReview({
        owner: this.owner,
        repo: this.repo,
        pull_number: this.prNumber,
        body,
        event: 'COMMENT',
      });

      this.logger.info(`Review comment posted on PR #${this.prNumber}`);
    } catch (error) {
      this.logger.error(`Failed to post review comment on PR #${this.prNumber}`, { error });
      throw error;
    }
  }

  private formatBlockedFilesComment(blockedFiles: BlockedFileResult[]): string {
    const lines: string[] = [
      '## ⚠️ Purview Data Security — Blocked Content Detected',
      '',
      'The following file(s) were flagged by data security policies and **blocked**:',
      '',
      '| File | Action |',
      '|------|--------|',
    ];

    for (const bf of blockedFiles) {
      for (const pa of bf.policyActions) {
        const action = pa.restrictionAction || pa.action;
        lines.push(`| \`${bf.filePath}\` | ${action} |`);
      }
    }

    lines.push('', '> This comment was generated by the Purview GitHub Action.');
    return lines.join('\n');
  }
}
